version: "3"

services:
  postgresql:
    image: postgres:14
    container_name: app_db
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - 5432:5432
    volumes:
      - ./config/postgres/initdb:/docker-entrypoint-initdb.d
volumes:
  database:
    driver: local
