name: PR Checks
on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=2g -Dkotlin.daemon.jvm.options=-Xmx1500m"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_SCHEMA: ${{ secrets.DATABASE_SCHEMA }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run ComposeUp
        run: ./gradlew composeUp
      - name: Run FlywayMigrate
        run: ./gradlew flywayMigrate
      - name: Run jooqCodegen
        run: ./gradlew jooqCodegen
      - name: Run detekt
        run: ./gradlew detekt
      - name: Run test
        run: ./gradlew test
      - name: Run koverVerify
        run: ./gradlew koverVerify
      - name: Run koverReport
        run: ./gradlew koverHtmlReport
      - name: Run ComposeDown
        if: always()
        run: ./gradlew composeDown
      - name: Archive coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/reports/kover/html
